# Generated by Django 6.0.6 on 2026-06-15 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=150)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptoms', models.JSONField(default=list)),
                ('symptoms_count', models.PositiveIntegerField(default=0)),
                ('predictions', models.JSONField(default=list)),
                ('top_disease', models.CharField(default='', max_length=200)),
                ('top_probability', models.FloatField(default=0)),
                ('top_severity', models.CharField(blank=True, default='', max_length=100)),
                ('top_specialist', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Session',
                'verbose_name_plural': 'Prediction Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
