# Generated by Django 6.0.5 on 2026-06-14 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('gastro', 'Gastrointestinal'), ('hepato', 'Hepatology')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('precautions', models.JSONField(blank=True, default=list)),
                ('specialist', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('severity_weight', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=150)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptoms', models.JSONField()),
                ('symptoms_count', models.PositiveIntegerField(default=0)),
                ('predictions', models.JSONField()),
                ('top_disease_name', models.CharField(max_length=200)),
                ('top_probability', models.FloatField()),
                ('top_severity', models.CharField(blank=True, max_length=100)),
                ('top_specialist', models.CharField(blank=True, max_length=200)),
                ('top_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_sessions', to='predictor.disease')),
            ],
            options={
                'verbose_name': 'Prediction Session',
                'verbose_name_plural': 'Prediction Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.register')),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
    ]
